variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # Repo configs
  GIT_CLONE_PATH: "/builds/it-asset-management-app"
  SOURCE_REPO_URL: "https://gitlab.com/ohjelmistotuotantoprojekti-tx00cf81-3012-r11/it-asset-management-app"
  MIRROR_REPO_URL: "gitlab.metropolia.fi/linusw/it-asset-management-app.git"
  # Secrets
  GIT_COMMIT_NAME: "GitLab CI on behalf of Linus Willner"
  GIT_COMMIT_EMAIL: $GIT_COMMIT_EMAIL
  METROPOLIA_GITLAB_TOKEN: $METROPOLIA_GITLAB_TOKEN

stages:
  - build
  - mirror
  - deploy

image: maven:3.8.2-adoptopenjdk-16

cache:
  paths:
    - .m2/repository

build-and-test:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS verify

mirror-to-metropolia-gitlab:
  stage: mirror
  script:
    - cd $GIT_CLONE_PATH
    - export COMMIT_SHA_LONG=$(git rev-parse HEAD)
    - export COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)
    - export BRANCH=$(git name-rev --name-only $COMMIT_SHA_LONG)
    - git checkout -b $BRANCH
    - git config --global user.name "$GIT_COMMIT_NAME"
    - git config --global user.email "$GIT_COMMIT_EMAIL"
    - git remote add metropolia https://gitlab-ci-token:$METROPOLIA_GITLAB_TOKEN@$MIRROR_REPO_URL
    - git add --all
    - git commit -m "Mirrored commit $COMMIT_SHA_SHORT" -m "Mirrored commit $SOURCE_REPO_URL/-/commit/$COMMIT_SHA_LONG"
    - git push metropolia $BRANCH

pages:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS javadoc:aggregate
    - mv ./target/site/apidocs/ public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
