version: "3"
services:
  postgresql:
    container_name: postgresql
    image: "postgres:latest"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devices
    ports:
      - "5432:5432"